name: diana
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  # 播放器
  video_player: ^2.4.7
  chewie: ^1.3.5
  # 保持屏幕不息屏
  wakelock: ^0.6.2
  # 全局设置点击空白区域隐藏键盘
  flutter_keyboard_visibility: ^5.4.0
  flutter: 
    sdk: flutter
  # 多国语言，解决输入框中语言切换问题
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

